// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz6ciJ8E971nPv5jTi1hCbhkPBqr7jeuw',
    appId: '1:681076508892:web:54ecef731550670b760c19',
    messagingSenderId: '681076508892',
    projectId: 'faceauth-5a652',
    authDomain: 'faceauth-5a652.firebaseapp.com',
    storageBucket: 'faceauth-5a652.appspot.com',
    measurementId: 'G-XG1DQ8MBR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPVo5sWOGNNLWxQaDID0LuWAq4Y0BLyd8',
    appId: '1:681076508892:android:2a32a355ee2b0f0e760c19',
    messagingSenderId: '681076508892',
    projectId: 'faceauth-5a652',
    storageBucket: 'faceauth-5a652.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU7Fni21OhJwVicUCDQpBWd6pjOwRQ2Uc',
    appId: '1:681076508892:ios:d9fe558a0bc19370760c19',
    messagingSenderId: '681076508892',
    projectId: 'faceauth-5a652',
    storageBucket: 'faceauth-5a652.appspot.com',
    iosBundleId: 'com.example.faceAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU7Fni21OhJwVicUCDQpBWd6pjOwRQ2Uc',
    appId: '1:681076508892:ios:d9fe558a0bc19370760c19',
    messagingSenderId: '681076508892',
    projectId: 'faceauth-5a652',
    storageBucket: 'faceauth-5a652.appspot.com',
    iosBundleId: 'com.example.faceAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz6ciJ8E971nPv5jTi1hCbhkPBqr7jeuw',
    appId: '1:681076508892:web:ffa4c2b5d68c0947760c19',
    messagingSenderId: '681076508892',
    projectId: 'faceauth-5a652',
    authDomain: 'faceauth-5a652.firebaseapp.com',
    storageBucket: 'faceauth-5a652.appspot.com',
    measurementId: 'G-B6JQXLYXLN',
  );
}
